/**
 * MASSIVE SEED using Firebase Client SDK with authentication
 * Works within Firestore security rules
 */

import { initializeApp } from 'firebase/app';
import { getAuth, signInWithEmailAndPassword } from 'firebase/auth';
import { getFirestore, collection, doc, setDoc, addDoc, serverTimestamp, Timestamp, updateDoc, arrayUnion, increment } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: 'AIzaSyAEwmgiNRIK_6uIMHbZOpM-u77Am-sy8gk',
  authDomain: 'demand-c5b0d.firebaseapp.com',
  projectId: 'demand-c5b0d',
  storageBucket: 'demand-c5b0d.firebasestorage.app',
  messagingSenderId: '185495150558',
  appId: '1:185495150558:web:6980111a5d948cbd04474f',
};

const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

function randomDate(monthsBack: number): Date {
  const now = Date.now();
  const past = now - monthsBack * 30 * 24 * 60 * 60 * 1000;
  return new Date(past + Math.random() * (now - past));
}
function randomItem<T>(arr: T[]): T { return arr[Math.floor(Math.random() * arr.length)]; }
function randomInt(min: number, max: number): number { return Math.floor(Math.random() * (max - min + 1)) + min; }

// All demand data
const DEMANDS = [
  { id: 'demand_001', title: 'Apple Must Support Right-to-Repair for All Devices', description: 'Apple has systematically made it harder for consumers and independent repair shops to fix their own devices. From proprietary screws to parts pairing that disables functionality, Apple\'s repair restrictions cost consumers billions annually and create massive e-waste.\n\nWe demand that Apple:\n1. End all parts pairing restrictions\n2. Make genuine replacement parts available at fair prices\n3. Publish complete repair manuals\n4. Remove software locks on non-Apple parts\n5. Support federal right-to-repair legislation\n\nThe average iPhone repair at an Apple Store costs 2-3x what an independent shop would charge. This artificial monopoly hurts consumers, destroys small businesses, and contributes to 50 million tons of e-waste annually. Apple generated $394 billion in revenue. They can afford to let people fix their own devices.', targetCompany: 'Apple', category: 'Technology', successCriteria: 'Apple publicly commits to ending parts pairing and makes parts available to independent shops.', creatorName: 'David Park', status: 'active', coSignCount: 34521, tags: ['right-to-repair', 'e-waste', 'consumer-rights'], escalationStage: 'movement' },
  { id: 'demand_002', title: 'Google: Stop Tracking Users Without Meaningful Consent', description: 'Google\'s data collection practices have gone far beyond acceptable. Despite promises of transparency, Google continues to track user location, browsing habits, and personal information through dozens of hidden settings.\n\nWe demand:\n1. Single "Stop All Tracking" toggle\n2. Tracking opt-IN by default\n3. Stop dark patterns\n4. Clear data explanations\n5. One-click data deletion\n6. Stop cross-site tracking\n\nPrivacy is a fundamental right. Google made $307 billion by monetizing our data.', targetCompany: 'Google', category: 'Technology', successCriteria: 'Google implements single-click tracking opt-out and makes tracking opt-in by default.', creatorName: 'Chris Nakamura', status: 'active', coSignCount: 47832, tags: ['privacy', 'data-rights', 'tracking'], escalationStage: 'movement' },
  { id: 'demand_003', title: 'Amazon: Guarantee Safe Working Conditions in All Warehouses', description: 'Amazon warehouse workers face dangerous conditions. Injury rates are nearly double industry average. Workers report forced bathroom break skipping and impossible quotas.\n\nWe demand:\n1. Reduce injury rates to industry average\n2. Install climate control in ALL warehouses\n3. Eliminate dangerous quotas\n4. Unrestricted bathroom breaks\n5. Independent quarterly safety audits\n6. Full healthcare for work injuries\n7. End retaliation against safety reporters\n\nAmazon is worth $2 trillion. No excuse for these injury rates.', targetCompany: 'Amazon', category: 'Technology', successCriteria: 'Amazon reduces injury rates to industry average and submits to independent safety audits.', creatorName: 'Tyler Brooks', status: 'active', coSignCount: 52108, tags: ['worker-safety', 'labor-rights', 'warehouses'], escalationStage: 'movement' },
  { id: 'demand_004', title: 'Meta Must Make Algorithm Transparency a Default', description: 'Meta\'s algorithms maximize engagement at the expense of mental health. Internal research shows algorithms amplify harmful content and contribute to teen mental health crises.\n\nWe demand:\n1. Publish complete ranking signals\n2. Toggle for chronological feed\n3. Show WHY content was shown\n4. Stop amplifying harmful content\n5. Independent algorithmic audits\n6. Age verification for under 18\n\nMeta made $135 billion by keeping us scrolling. We deserve transparency.', targetCompany: 'Meta', category: 'Technology', successCriteria: 'Meta publishes algorithm signals, offers chronological feed, allows independent audits.', creatorName: 'Priya Sharma', status: 'active', coSignCount: 38945, tags: ['algorithm-transparency', 'mental-health', 'social-media'], escalationStage: 'movement' },
  { id: 'demand_005', title: 'End Overdraft Fees: Banks Must Stop Profiting from Poverty', description: 'Major US banks charge over $30 billion in overdraft fees annually, hitting low-income Americans hardest. JPMorgan Chase collected $1.9 billion in overdraft fees. 80% of fees come from just 9% of account holders.\n\nWe demand:\n1. Eliminate all overdraft fees\n2. Real-time balance notifications\n3. Free short-term credit for small overdrafts\n4. Stop transaction reordering\n5. Refund past 12 months fees\n\nChase made $50 billion profit. They don\'t need overdraft fees.', targetCompany: 'JPMorgan Chase', category: 'Finance', successCriteria: 'JPMorgan Chase eliminates overdraft fees and implements real-time balance alerts.', creatorName: 'Fatima Al-Rashid', status: 'active', coSignCount: 28734, tags: ['overdraft-fees', 'banking', 'financial-justice'], escalationStage: 'campaign' },
  { id: 'demand_006', title: 'Cap Insulin Prices at $35 for All Americans', description: 'Insulin costs $300+ per vial in the US vs $30 in Canada. 1.3 million Americans ration insulin. Eli Lilly raised prices 1,200% while production costs decreased.\n\nWe demand:\n1. Cap ALL insulin at $35/month regardless of insurance\n2. Eliminate patient assistance barriers\n3. Publish manufacturing cost data\n4. Stop lobbying against drug price regulation\n5. Hardship fund for uninsured diabetics\n\nInsulin patent was sold for $1. People are dying because they can\'t afford it.', targetCompany: 'Eli Lilly', category: 'Healthcare', successCriteria: 'Eli Lilly caps all insulin at $35/month for all Americans.', creatorName: 'Emma Rodriguez', status: 'active', coSignCount: 67234, tags: ['insulin', 'drug-pricing', 'healthcare'], escalationStage: 'crisis' },
  { id: 'demand_007', title: 'UnitedHealth: Stop Denying Claims Using AI Algorithms', description: 'UnitedHealth uses AI to auto-deny claims with 90% error rate on appeal. Patients denied chemo, surgery, therapy without human review.\n\nWe demand:\n1. Cease AI claim denials\n2. Physician review for ALL denials\n3. 48-hour appeal processing\n4. Publish denial/overturn rates\n5. Compensate harmed patients\n6. Independent AI audit\n\nHealthcare decisions by doctors, not profit-optimizing algorithms.', targetCompany: 'UnitedHealth Group', category: 'Healthcare', successCriteria: 'UnitedHealth stops AI denials, requires physician review, publishes data.', creatorName: 'Tanya Okafor', status: 'active', coSignCount: 43567, tags: ['insurance-denials', 'AI', 'healthcare'], escalationStage: 'movement' },
  { id: 'demand_008', title: 'McDonald\'s: Pay All Workers a Living Wage of $20/hr', description: 'McDonald\'s workers earn $11-13/hr while the company makes $25B revenue. CEO earned $18M. $6B on buybacks instead of workers.\n\nWe demand:\n1. $20/hour for ALL including franchise\n2. Healthcare for 25+ hour workers\n3. Predictable scheduling\n4. End non-competes for hourly workers\n5. 401(k) matching\n\nWhen workers can\'t eat where they work, something is broken.', targetCompany: 'McDonald\'s', category: 'Food', successCriteria: 'McDonald\'s commits to $20/hr including franchise employees.', creatorName: 'Derek Foster', status: 'active', coSignCount: 31245, tags: ['living-wage', 'fast-food', 'worker-rights'], escalationStage: 'campaign' },
  { id: 'demand_009', title: 'DoorDash: Transparent Pricing and Fair Driver Pay', description: 'On a $30 order, DoorDash takes $13.50 in fees while drivers get $4.50 before expenses.\n\nWe demand:\n1. Fee breakdown on every order\n2. $15/hr minimum for drivers after expenses\n3. 15% cap on restaurant commissions\n4. Show actual vs DoorDash prices\n5. Stop using tips as base pay\n6. Driver accident insurance', targetCompany: 'DoorDash', category: 'Food', successCriteria: 'DoorDash implements fee transparency and $15/hr driver minimum.', creatorName: 'Kevin Tran', status: 'active', coSignCount: 18923, tags: ['gig-economy', 'food-delivery', 'transparency'], escalationStage: 'campaign' },
  { id: 'demand_010', title: 'Kroger: End Grocery Shrinkflation and Hidden Price Increases', description: 'Kroger embraces shrinkflation — reducing sizes while maintaining prices. Executives discussed strategies to raise prices beyond inflation.\n\nWe demand:\n1. Prominent unit pricing on ALL labels\n2. "Size Changed" labels\n3. Cap private-label increases\n4. Quarterly transparency reports\n5. Consumer advisory board', targetCompany: 'Kroger', category: 'Food', successCriteria: 'Kroger implements unit pricing and shrinkflation labeling.', creatorName: 'Mei-Lin Wu', status: 'active', coSignCount: 22456, tags: ['shrinkflation', 'grocery', 'transparency'], escalationStage: 'campaign' },
  { id: 'demand_011', title: 'ExxonMobil: Honor Your Climate Pledges or Face Accountability', description: 'Exxon funded climate denial for decades. 2025 emissions INCREASED 3% despite net-zero pledges. Carbon capture under 1% of capex.\n\nWe demand:\n1. Binding reduction plan with annual targets\n2. 20% capex to renewables by 2027\n3. Stop funding climate denial\n4. $10B fund for affected communities\n5. Tie exec pay to emissions targets\n6. Annual independent audits', targetCompany: 'ExxonMobil', category: 'Energy', successCriteria: 'ExxonMobil publishes binding plan and allocates 20% to renewables.', creatorName: 'Lisa Thompson', status: 'active', coSignCount: 45678, tags: ['climate', 'emissions', 'greenwashing'], escalationStage: 'movement' },
  { id: 'demand_012', title: 'Duke Energy: Stop Raising Utility Rates on Fixed-Income Seniors', description: 'Duke Energy raised rates 47% over a decade while reporting record profits. Monopoly means customers can\'t switch.\n\nWe demand:\n1. Freeze rates for below 200% poverty level\n2. Progressive rate structure\n3. Cap exec pay at 50x median worker\n4. Invest increases in renewables\n5. Community oversight board', targetCompany: 'Duke Energy', category: 'Energy', successCriteria: 'Duke Energy freezes rates for low-income customers.', creatorName: 'Christopher Lee', status: 'active', coSignCount: 12345, tags: ['utility-rates', 'energy', 'seniors'], escalationStage: 'campaign' },
  { id: 'demand_013', title: 'Tesla: Standardize EV Charging and Open the Supercharger Network', description: 'Tesla\'s proprietary network fragments EV charging infrastructure.\n\nWe demand:\n1. Open 100% Superchargers to all EVs at equal pricing\n2. Adopt unified NACS standards\n3. Equal speeds for all brands\n4. Open API for availability\n5. Partner on open standard', targetCompany: 'Tesla', category: 'Energy', successCriteria: 'Tesla opens all Superchargers at equal pricing.', creatorName: 'Sofia Petrov', status: 'active', coSignCount: 19876, tags: ['ev-charging', 'electric-vehicles', 'climate'], escalationStage: 'campaign' },
  { id: 'demand_014', title: 'Walmart: End Poverty Wages and Provide Healthcare for All Workers', description: 'Walmart: 2.1M workers, thousands on government assistance. Taxpayers subsidize $6.2B/year. Average wage $14.50/hr.\n\nWe demand:\n1. $20/hour minimum\n2. Healthcare for 20+ hour workers\n3. 3-week advance schedules\n4. 30hr minimum for full-time\n5. Stop union-busting', targetCompany: 'Walmart', category: 'Retail', successCriteria: 'Walmart raises to $20/hr and provides healthcare.', creatorName: 'Tamara Jones', status: 'active', coSignCount: 41234, tags: ['living-wage', 'healthcare', 'retail'], escalationStage: 'movement' },
  { id: 'demand_015', title: 'AT&T: End Data Caps and Hidden Fees on All Plans', description: 'AT&T "unlimited" isn\'t unlimited. Hidden fees add $15-20/month. Actual costs 31% higher than advertised.\n\nWe demand:\n1. Eliminate data caps on unlimited\n2. Include ALL fees in prices\n3. Stop throttling\n4. Honest speed tests\n5. Cancel without penalty when service fails', targetCompany: 'AT&T', category: 'Telecom', successCriteria: 'AT&T eliminates data caps and includes all fees in prices.', creatorName: 'Nate Sullivan', status: 'active', coSignCount: 25678, tags: ['data-caps', 'hidden-fees', 'telecom'], escalationStage: 'campaign' },
  { id: 'demand_016', title: 'Comcast: Deliver the Broadband Speeds You Promise', description: 'Comcast delivers 40-60% of advertised speeds during peak hours despite billions in subsidies.\n\nWe demand:\n1. 90% of advertised speeds 95% of time\n2. Automatic credits for failures\n3. End data caps\n4. 30% revenue to infrastructure\n5. Fulfill subsidy commitments\n6. Real-time performance data', targetCompany: 'Comcast', category: 'Telecom', successCriteria: 'Comcast guarantees 90% of advertised speeds.', creatorName: 'Bethany Cruz', status: 'active', coSignCount: 19234, tags: ['broadband', 'internet-speed', 'telecom'], escalationStage: 'campaign' },
  { id: 'demand_017', title: 'Netflix: Stop the Price Hikes and Ad-Tier Degradation', description: 'Netflix raised prices 8 times in a decade. Ad-free now $23/month. Content libraries shrunk.\n\nWe demand:\n1. Freeze ad-free prices 24 months\n2. No ads on ad-free plans\n3. Publish content metrics\n4. Allow permanent downloads\n5. Restore family sharing', targetCompany: 'Netflix', category: 'Entertainment', successCriteria: 'Netflix freezes prices 24 months.', creatorName: 'Will Hernandez', status: 'active', coSignCount: 35678, tags: ['streaming', 'price-hikes', 'entertainment'], escalationStage: 'movement' },
  { id: 'demand_018', title: 'Ticketmaster: End the Monopoly on Live Event Tickets', description: 'Ticketmaster monopoly: 2-3x face value, 30%+ fees, dynamic pricing, rampant scalping.\n\nWe demand:\n1. Cap fees at 10%\n2. Eliminate dynamic pricing\n3. Effective anti-bot measures\n4. All fees upfront\n5. Face-value-only transfers\n6. Support breaking up monopoly', targetCompany: 'Ticketmaster', category: 'Entertainment', successCriteria: 'Ticketmaster caps fees at 10% and eliminates dynamic pricing.', creatorName: 'Malik Robinson', status: 'active', coSignCount: 58432, tags: ['ticketing', 'monopoly', 'live-events'], escalationStage: 'movement' },
  { id: 'demand_019', title: 'Navient: End Predatory Student Loan Servicing Practices', description: 'Navient steers borrowers into costly plans, makes forgiveness difficult. $1.7 trillion in student debt.\n\nWe demand:\n1. Proactively offer cheapest options\n2. Process PSLF in 30 days\n3. Apply to highest interest first\n4. Accurate forgiveness info\n5. Compensate affected borrowers\n6. 5-minute call answer times', targetCompany: 'Navient', category: 'Finance', successCriteria: 'Navient proactively offers cheapest options.', creatorName: 'Brandon Mitchell', status: 'active', coSignCount: 23456, tags: ['student-loans', 'predatory-lending'], escalationStage: 'campaign' },
  { id: 'demand_020', title: 'Bank of America: Stop Charging Late Fees on Credit Cards', description: 'BofA charges $41 per late payment, creating debt spirals. BofA made $30B profit.\n\nWe demand:\n1. Eliminate late fees\n2. 10-day grace period\n3. Multiple reminders\n4. Auto minimum payment\n5. Stop rate increases for single late payments', targetCompany: 'Bank of America', category: 'Finance', successCriteria: 'BofA eliminates late fees.', creatorName: 'Ryan O\'Brien', status: 'active', coSignCount: 16789, tags: ['late-fees', 'credit-cards', 'banking'], escalationStage: 'campaign' },
  { id: 'demand_021', title: 'Shein: Disclose Your Full Supply Chain and Labor Practices', description: 'Shein workers: 18-hour days, 3 cents/garment. 6.3M tons CO2/year. No transparency.\n\nWe demand:\n1. Publish all factories/suppliers\n2. Independent labor audits\n3. Minimum wage compliance\n4. Chemical disclosure\n5. Take-back program\n6. Environmental assessments', targetCompany: 'Shein', category: 'Retail', successCriteria: 'Shein publishes supply chain and submits to audits.', creatorName: 'Ingrid Larsson', status: 'active', coSignCount: 29876, tags: ['fast-fashion', 'supply-chain', 'labor-rights'], escalationStage: 'campaign' },
  // VICTORIES
  { id: 'demand_022', title: 'Microsoft: Make Windows Updates Non-Disruptive', description: 'After 15,000+ co-signers, Microsoft announced policy changes in January 2026 allowing users to defer all non-security updates indefinitely. This is what organized consumer pressure looks like.', targetCompany: 'Microsoft', category: 'Technology', successCriteria: 'Users get full control over update timing.', creatorName: 'David Park', status: 'met', coSignCount: 15234, tags: ['windows', 'updates', 'victory'], escalationStage: 'movement', victoryStatement: 'Microsoft eliminated forced restarts for non-security updates.' },
  { id: 'demand_023', title: 'Spotify: Increase Artist Royalty Payments', description: 'After 20,000 co-signers, Spotify announced 40% royalty increase for independent artists in December 2025.', targetCompany: 'Spotify', category: 'Entertainment', successCriteria: 'Spotify increases per-stream royalty by 30%+.', creatorName: 'Malik Robinson', status: 'met', coSignCount: 21456, tags: ['music', 'artist-pay', 'victory'], escalationStage: 'campaign', victoryStatement: 'Spotify increased independent artist royalties by 40%.' },
  { id: 'demand_024', title: 'Adobe: End Surprise Cancellation Fees on Creative Cloud', description: '30,000+ co-signers in two months. Adobe eliminated cancellation fees in November 2025.', targetCompany: 'Adobe', category: 'Technology', successCriteria: 'Adobe eliminates early termination fees.', creatorName: 'Alex Rivera', status: 'met', coSignCount: 32145, tags: ['subscription-traps', 'victory'], escalationStage: 'movement', victoryStatement: 'Adobe eliminated all early termination fees.' },
  { id: 'demand_025', title: 'Uber: Provide Transparent Fare Breakdowns to Riders', description: '18,000 co-signers. Uber now shows complete fare breakdowns on every ride since October 2025.', targetCompany: 'Uber', category: 'Technology', successCriteria: 'Uber shows complete fare breakdown.', creatorName: 'Rashid Hassan', status: 'met', coSignCount: 18234, tags: ['ride-sharing', 'transparency', 'victory'], escalationStage: 'campaign', victoryStatement: 'Uber now shows complete fare breakdowns on every ride.' },
  // More active
  { id: 'demand_026', title: 'Amazon: End Subscription Traps — Make Cancellation Easy', description: 'Prime cancellation requires 6+ screens with dark patterns. 14% fail to cancel.\n\nWe demand one-click cancellation, no dark patterns, renewal reminders, partial refunds.', targetCompany: 'Amazon', category: 'Retail', successCriteria: 'Amazon implements one-click cancellation.', creatorName: 'Aisha Okonkwo', status: 'active', coSignCount: 27654, tags: ['subscription-traps', 'dark-patterns'], escalationStage: 'campaign' },
  { id: 'demand_027', title: 'All Hospitals: Publish Real Prices Before Treatment', description: 'Only 36% hospitals comply with transparency rules. Medical debt = #1 bankruptcy cause.\n\nWe demand complete price lists, binding estimates, honored prices, financial counseling, no surprise billing.', targetCompany: 'UnitedHealth Group', category: 'Healthcare', successCriteria: 'Hospitals achieve 100% price transparency.', creatorName: 'Olivia Chang', status: 'active', coSignCount: 38765, tags: ['hospital-pricing', 'transparency'], escalationStage: 'movement' },
  { id: 'demand_028', title: 'Meta: Protect Children from Algorithm-Driven Content Addiction', description: '32% teen girls say Instagram worsens body image.\n\nWe demand age verification, no algorithms for under 16, time limits, no youth ads, research funding, safety audits.', targetCompany: 'Meta', category: 'Technology', successCriteria: 'Meta implements age verification and disables algorithms for minors.', creatorName: 'Michelle Patel', status: 'active', coSignCount: 54321, tags: ['child-safety', 'social-media', 'mental-health'], escalationStage: 'movement' },
  { id: 'demand_029', title: 'Comcast: End Contract Lock-Ins and Equipment Rental Fees', description: '$14/month modem rental for $80 equipment. Steep termination fees.\n\nWe demand month-to-month only, customer equipment, capped rental, full price disclosure.', targetCompany: 'Comcast', category: 'Telecom', successCriteria: 'Comcast ends contracts.', creatorName: 'Nate Sullivan', status: 'active', coSignCount: 14567, tags: ['contracts', 'equipment-fees', 'telecom'], escalationStage: 'campaign' },
  { id: 'demand_030', title: 'Google: Stop Burying Organic Search Results Under Ads', description: '4-5 ads before organic results. Mobile: ads fill entire first screen. $192B search ad revenue.\n\nWe demand max 2 ads/page, clear labeling, 20% max screen, quality metrics, ad-free option.', targetCompany: 'Google', category: 'Technology', successCriteria: 'Google limits search ads to 2 per page.', creatorName: 'Priya Sharma', status: 'active', coSignCount: 22345, tags: ['search', 'ads', 'internet'], escalationStage: 'campaign' },
  { id: 'demand_031', title: 'Pesticide Transparency: Require Full Disclosure on All Produce', description: '70% conventional produce has pesticide residues. Many chemicals banned in EU.\n\nWe demand disclosure on all produce, QR codes, priority low-pesticide suppliers, phase out neonicotinoids.', targetCompany: 'Kroger', category: 'Food', successCriteria: 'Grocers implement pesticide disclosure.', creatorName: 'Luis Gutierrez', status: 'active', coSignCount: 11234, tags: ['pesticides', 'food-safety'], escalationStage: 'petition' },
  { id: 'demand_032', title: 'Apple: End Planned Obsolescence in iPhones', description: 'Apple slows old iPhones, makes batteries non-replaceable. Paid $500M settlement.\n\nWe demand 7-year support, $29 battery replacement, no throttling, benchmarks, stability mode.', targetCompany: 'Apple', category: 'Technology', successCriteria: 'Apple commits to 7-year support.', creatorName: 'Omar Farouk', status: 'active', coSignCount: 28765, tags: ['planned-obsolescence', 'e-waste'], escalationStage: 'campaign' },
  { id: 'demand_033', title: 'AI Companies: Mandatory Transparency in AI Training Data', description: 'AI companies train on scraped data without consent. No compensation for creators.\n\nWe demand training data documentation, opt-out, creator compensation, independent audits, AI content labeling.', targetCompany: 'Google', category: 'Technology', successCriteria: 'AI companies publish training data docs.', creatorName: 'Kwame Asante', status: 'active', coSignCount: 33456, tags: ['AI', 'training-data', 'transparency'], escalationStage: 'campaign' },
];

async function seed() {
  console.log('🚀 Starting massive seed...\n');
  
  // Sign in
  const cred = await signInWithEmailAndPassword(auth, 'seed-admin@demand.app', 'SeedAdmin2026!!');
  const uid = cred.user.uid;
  console.log(`🔑 Signed in as ${uid}\n`);

  // Seed demands - the rules require creatorId == auth.uid and timestamps == serverTimestamp
  console.log('📋 Seeding demands...');
  let count = 0;
  for (const demand of DEMANDS) {
    try {
      const demandRef = doc(db, 'demands', demand.id);
      const coSignerIds = Array.from({length: Math.min(demand.coSignCount, 50)}, (_, i) => `user_${String(i + 1).padStart(3, '0')}`);
      
      await setDoc(demandRef, {
        title: demand.title,
        description: demand.description,
        targetCompany: demand.targetCompany,
        category: demand.category || 'General',
        successCriteria: demand.successCriteria,
        creatorId: uid, // Must match auth.uid per rules
        creatorName: demand.creatorName,
        status: demand.status,
        visibility: 'public',
        coSigners: coSignerIds,
        coSignCount: demand.coSignCount,
        tags: demand.tags || [],
        escalationStage: demand.escalationStage || 'petition',
        currentSpokespersonId: '',
        spokespersonVotes: [],
        spokespersonVotingOpen: false,
        activeNegotiations: [],
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
        ...(demand.status === 'met' ? { victoryStatement: demand.victoryStatement } : {}),
      });
      count++;
      process.stdout.write(`\r  ${count}/${DEMANDS.length}`);
    } catch (e: any) {
      console.error(`\n  ❌ ${demand.id}: ${e.message}`);
    }
  }
  console.log(`\n  ✅ ${count} demands created`);

  console.log('\n🎉 SEED COMPLETE!');
  process.exit(0);
}

seed().catch(e => { console.error(e); process.exit(1); });
